format = '[Ty](green)[@](red)[NixOS](blue)[:](red)$directory$git_branch$git_status$nix_shell$package$python$rust[\]](green)[†](red) $status[ >](blue)'

[directory]
style = "yellow"
truncation_length = 3
fish_style_pwd_dir_length = 1

# Git branch appearance
[git_branch]
symbol = "🌿 "
style = "bold purple"
format = "on [$symbol$branch]($style) "

# Git status emojis
[git_status]
conflicted = "💥 "
ahead = "🚀 "
behind = "🐢 "
cant_diverge = "↕️ "
diverged = "🔱 "
untracked = "🤷 "
staged = "📦 "
modified = "📝 "
renamed = "🚚 "
deleted = "🗑️ "
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"

# Python language indicator
[python]
symbol = "🐍 "
style = "bold yellow"
disabled = false 
format = "via [$symbol$version]($style) "

# Rust language indicator
[rust]
symbol = "🦀 "
style = "bold red"
disabled = false
format = "via [$symbol$version]($style) "

[nix_shell]
disabled = false
format = "via [❄️ $state $name]($style) "
style = "bold blue"

[status]
disabled = false
format = '[\[$int\]](bold red) '
